prose:
  rooturl: "_posts"
  siteurl: "https://casedepart-ludotheque.github.io"
  media: "assets/images"
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Titre"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "category"
        field:
          element: "select"
          label: "Catégorie"
          options:
            - jardin
            - pommier
            - greffe