backend:
  name: github
  repo: casedepart-ludotheque/casedepart-ludotheque.github.io
  branch: main  # ou master
  auth_scope: repo

media_folder: "img/uploads"        # où tu veux stocker les images
public_folder: "/img/uploads"

collections:
  - name: "posts"
    label: "Articles"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "config_site"
    label: "Fichier de configuration"
    files:
      - label: "Site config"
        name: "site_config"
        file: "_data/config.yml"
        fields:
          - { label: "Titre du site", name: "site_title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
